trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore eShopOnWeb.sln
  displayName: 'Restore packages'

- script: dotnet build eShopOnWeb.sln --configuration $(buildConfiguration) --no-restore
  displayName: 'Build solution'

- script: dotnet test eShopOnWeb.sln --configuration $(buildConfiguration) --no-build --logger trx
  displayName: 'Run unit tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/*.trx'
    testRunTitle: 'Unit Tests'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: 'src/Web/Web.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  displayName: 'Publish Web project'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
